[package]
name = "rocket_rs"
version = "0.1.0"
edition = "2021"

[lib]
name = "rocket_rs"
path = "rs/src/lib.rs"  # Rust source code path
crate-type = ["cdylib"]

[dependencies]
ndarray = "0.15.6"
numpy = "0.20.0"
pyo3 = "0.20.0"
