[package]
name = "rocket_rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "rocket_rs"
path = "rs/src/lib.rs"  # Rust source code path
crate-type = ["cdylib"]

[dependencies]
pyo3 = "0.20.0"
